home/urls.py
from django.urls import path
from home import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('skills/', include('skills.urls')),
]

skills/urls.py
from skills import views
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'skills'
urlpatterns = [
    path('', views.skills, name='skills'),
    path('<int:category_id>', views.skills_recipe, name='skills_recipe'),
]

urlpatterns += staticfiles_urlpatterns()

home/models.py
from django.db import models


# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home/home.html')

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section>
        <div class="main-container" >
            <div class="image" data-aos="fade-down" data-aos-delay="100">
                <img src="{% static 'images/MyP.png' %}" alt="My Picture">
            </div>
            <div class="content">
                    <h1 data-aos="fade-left" data-aos-delay="100">Hello im <span>Reggie</span></h1>
                    <div class="typewriter" data-aos="fade-right" data-aos-delay="300">I'm a <span class="typewriter-text">|</span><label for=""></label></div>
                    <p data-aos="flip-down" data-aos-delay="100">Greetings from beyond the grave! As a senior high school student by day and a brain-craving zombie by night,
                        I’m here to share my unique journey through the corridors of both education and the afterlife.
                        I’m a zombie who’s dedicated to learning and growing, despite my undead status. Balancing my studies with my nocturnal hunger for brains,
                        I strive to make the most of my high school experience, even if it means dragging my feet a bit more than usual.</p>
                    <div class="social-link">
                        <a href="#" data-aos="fade-up" data-aos-delay="100"><i class='bx bxl-github'></i></a>
                        <a href="#" data-aos="fade-up" data-aos-delay="100"><i class='bx bxl-facebook-square' ></i></a>
                        <a href="#" data-aos="fade-up" data-aos-delay="100"><i class='bx bxl-linkedin-square' ></i></a>
                    </div>
                    <button data-aos="zoom-out" data-aos-delay="100">Hire me</button>
            </div>
        </div>
    </section>
{% endblock %}

skills/templates/skills/skills.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container skills">
        <h2>Skills</h2>
    <div class="skills-list">
        {% for skill in skill_list %}
        	<div class="item">
                <h4>{{ skill.skill_name }}</h4>
                <img src="" alt="">
                <p>{{ skill.description }}</p>
                <a href="{% url 'skills:skills_recipe' skill.id%}">Read More</a>
            </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}

skills/templates/skills/skills_recipe.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container skills-recipe">
        <h3>{{ skill_category }}</h3>
        {% for category in categories %}
            <div class="skills-recipe-container">
                <h4>{{ category.category_name }}</h4>
                <p>{{ category.description }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home/home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/skills/skills.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/skills/skill_recipes.css' %}">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <title>Home</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav>
        <div class="nav-container">
            <div class="logo" data-aos="zoom-in">
                Reggie <span>Ambrocio</span>
            </div>
            <div class="nav-pc">
                <div class="link" data-aos="fade-up" data-aos-delay="100"><a href="{% url 'home:home' %}">Home</a></div>
                <div class="link" data-aos="fade-down" data-aos-delay="200"><a href="{% url 'skills:skills' %}">Skills</a></div>
                <div class="link" data-aos="fade-up" data-aos-delay="300"><a href="#">Experience</a></div>
                <div class="link" data-aos="fade-down" data-aos-delay="400"><a href="#">Services</a></div>
                <div class="link" data-aos="fade-up" data-aos-delay="500"><a href="#">Contact</a></div>
            </div>

        </div>
        <i class='bx bx-menu hamburg' onclick="hamburg()"></i>
        <div class="dropdown">
            <div class="links">
                <a href="{% url 'home:home' %}">Home</a>
                <a href="{% url 'skills:skills' %}">Skill</a>
                <a href="#">About</a>
                <a href="#">Contact</a>
                <i class='bx bx-x cancel' onclick="cancel()"></i>
            </div>
        </div>
        </div>

    </nav>

    {% block content %}

    {% endblock %}
    <script src="{% static 'javascript/script.js' %}"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init({
            offset:0,
            duration:1500,
            });
    </script>

</body>
</html>